-- Seed: the Trulinq roster (verified members from trulinqid.com plus Ahmad Khalid), the four rooms, and any posts and
-- endorsements that exist. Idempotent: every insert is on conflict do nothing. Seeded members have no login
-- (user_id is null); npm run admin -- create-user --member <slug> attaches one.

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('0542e68e-ae26-4a7e-ae34-252ae5e022ed'::uuid, 'tyler-shirakawa', 'Tyler Shirakawa', 'Tyler', 'CEO of Trulinq', 'CEO', 'Trulinq', 'Hilo', '', 'United States', 19.7241, -155.0868, 'Marketing', '36 Yr old entrepreneur based in Hawaii. Background is marketing, trading, and pemf sales and peptides.', '', 'Investors, potential business partners.', 'trulinqid.com', true, null, null, 'verified', '2026-09-01', 'E9EAF5', 2, 4, '2026-09-01', '2026-09-01T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('0542e68e-ae26-4a7e-ae34-252ae5e022ed'::uuid, 45, 20, 15, 0, 1, 746, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('ff8d19ca-d314-448f-a596-7de8f2b07d44'::uuid, 'maverick-kang-jr', 'Maverick kang Jr', 'Maverick', 'Credit Repair + Funding Coach', 'Owner', 'QUIK SCALE LLC', 'Phoenix', '', 'United States', 33.4484, -112.074, 'Consulting', 'Helping individuals and business owners strengthen their credit profiles, improve funding readiness, and access better financing opportunities. Focused on practical credit optimization, strategic funding preparation, and long-term financial positioning.', '', 'Credit Repair + Funding Clients', 'instagram.com/mavkangjr', true, null, null, 'verified', '2026-09-02', 'H3AX9K8C', 1, 0, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('ff8d19ca-d314-448f-a596-7de8f2b07d44'::uuid, 45, 20, 15, 0, 1, 746, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('bdf564c8-1639-490e-9317-043b0bed80a5'::uuid, 'michael-onwumere', 'Michael Onwumere', 'Michael', 'O’mere', '', 'O’mere', '', '', 'Canada', null, null, '', '', '', '', '', false, null, null, 'verified', '2026-09-02', 'B9ATF5AK', 0, 0, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('bdf564c8-1639-490e-9317-043b0bed80a5'::uuid, 45, 8, 0, 0, 1, 597, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('76250bba-25c8-4b1b-beab-aed41597925b'::uuid, 'preston-sinenci-jr', 'Preston Sinenci Jr', 'Preston', '', 'Founder', 'Preston Ventures', 'Honolulu', '', 'United States', 21.3069, -157.8583, 'Technology', 'Verified entrepreneur on Trulinq.', '', '', 'trulinqid.com', true, null, null, 'verified', '2026-09-02', 'QSMWGX56', 3, 0, '2026-03-31', '2026-03-31T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('76250bba-25c8-4b1b-beab-aed41597925b'::uuid, 45, 20, 15, 2, 1, 757, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('26011ade-a5ed-40b4-8208-4e31e2f1aff4'::uuid, 'makalea-medeiros', 'Makalea Medeiros', 'Makalea', 'Entrepreneur', 'Owner', 'Waiakoa enterprise LLC', 'Kula', 'Maui', 'United States', 20.7911, -156.3261, 'Direct sales/service', 'I’m Maka Medeiros, an entrepreneur from Maui focused on building businesses, investing in real estate, and creating multiple streams of income. My mission is to transition out of the traditional 9–5, build assets that generate long-term cash flow, and create financial freedom and generational wealth for my family. I’m here to surround myself with high-level thinkers, learn from people who have already achieved what I’m pursuing, and turn that knowledge into action.', '', 'Investors', 'instagram.com/makamedeiros', true, null, null, 'verified', '2026-09-03', 'V7L5UUUM', 1, 4, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('26011ade-a5ed-40b4-8208-4e31e2f1aff4'::uuid, 45, 20, 15, 0, 1, 746, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('9f0c35f7-554b-4b1b-bd5b-21cf6b91a075'::uuid, 'david', 'David', 'David', 'Building the first Binational AI Hyperscale north México Campus - A Cross Border AI Data Center', 'Chief Business Development Officer', 'KoridaIA', 'Richland', '', 'United States', 46.2857, -119.2845, 'Energy', 'With over 8 years of professional experience, including tenure as a sourcing specialist, high school teacher and energy industry consultant, I bring a diverse background to my role. I am passionate about fostering strong relationships and creating aligned, repeatable structures that meet the needs of brokers and clients. My mission is to connect buyers to sellers and vice versa.', 'Data center services, financing partners, renewable and sustainability energy projects, RWA’s, and tokenization companies.', 'Cofounders, data center experts, energy companies, funding experts', 'koridaia.mx', true, null, null, 'verified', '2026-09-02', 'NTFETAPJ', 1, 4, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('9f0c35f7-554b-4b1b-bd5b-21cf6b91a075'::uuid, 45, 20, 15, 0, 1, 746, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('7d88daa1-570a-4f1d-b32e-5c8005829b10'::uuid, 'chelsea-pferschy', 'Chelsea Pferschy', 'Chelsea', '', 'Realtor', 'CP', 'Honolulu', '', 'United States', 21.2934, -157.8283, 'Real Estate', '', '', 'General help and info', '', false, null, null, 'verified', '2026-09-02', 'HGX52W4Q', 3, 0, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('7d88daa1-570a-4f1d-b32e-5c8005829b10'::uuid, 45, 18, 0, 0, 1, 652, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('bf7df63c-af30-4099-98c4-26b73690a137'::uuid, 'palani-maharaj', 'Palani Maharaj', 'Palani', 'Son of one of the best Thai foods on Bigisland Hawaii', 'Cook/Co Owner', 'Ratcha Thai', 'Waikoloa', 'Hawaiʻi', 'United States', 19.9406, -155.7919, 'Restaurant', '', '', 'Connections', '', false, null, null, 'verified', '2026-09-02', '9ZKDALLR', 1, 0, '2026-09-02', '2026-09-02T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('bf7df63c-af30-4099-98c4-26b73690a137'::uuid, 45, 18, 0, 0, 1, 652, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values ('4533bad7-acd5-4705-96e8-2818861e7b9d'::uuid, 'omai-kofi', 'Omai Kofi', 'Omai', 'The Board Of Literacy', '', 'The Board Of Literacy', '', '', 'United States', null, null, '', '', '', '', '', false, null, null, 'verified', '2026-09-25', 'N9EUF5SY', 0, 0, '2026-09-25', '2026-09-25T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values ('4533bad7-acd5-4705-96e8-2818861e7b9d'::uuid, 45, 8, 0, 0, 0, 592, 'seed') on conflict (member_id) do nothing;

insert into members (id, slug, name, first_name, headline, role, company, city, region, country, lat, lng, industry, bio, offers, looking, website, website_verified, founded, photo, verification_status, verified_on, referral_code, followers, following, joined_on, created_at)
values (md5('trulinq:member:ahmad-khalid')::uuid, 'ahmad-khalid', 'Ahmad Khalid', 'Ahmad', '', 'Owner', 'Skybound Scaling', '', '', '', null, null, 'Marketing', 'Owner of Skybound Scaling. Web development and digital marketing: websites built to bring in customers, and the SEO and paid campaigns that keep them coming.', 'Web development, digital marketing (SEO, Google and Meta ads)', 'Founders and owners who want a site that brings in customers', 'skyboundscaling.com', true, 2025, null, 'verified', '2026-09-24', 'P5UQ2NJ3', 0, 0, '2026-09-20', '2026-09-20T12:00:00Z')
on conflict (slug) do nothing;
insert into member_scores (member_id, identity, profile, web, history, standing, total, source) values (md5('trulinq:member:ahmad-khalid')::uuid, 45, 15, 15, 0, 0, 713, 'seed') on conflict (member_id) do nothing;

insert into rooms (slug, name, emoji, topic, live, sort) values ('lounge', 'Executive Founder Circle', '', 'Private floor for verified entrepreneurs to connect and collaborate.', false, 0) on conflict (slug) do nothing;
insert into rooms (slug, name, emoji, topic, live, sort) values ('retail', 'Retail & E-Commerce Board', '', 'Storefronts, suppliers, fulfilment and omnichannel growth.', false, 1) on conflict (slug) do nothing;
insert into rooms (slug, name, emoji, topic, live, sort) values ('saas', 'SaaS & Technology Board', '', 'Product, pricing, churn and go to market for software founders.', false, 2) on conflict (slug) do nothing;
insert into rooms (slug, name, emoji, topic, live, sort) values ('trade', 'Trade & Logistics Board', '', 'Sourcing, freight, customs and cross border payments.', false, 3) on conflict (slug) do nothing;
