/* Bundles the Vercel function (server/vercel.ts and everything it imports) into plain JavaScript at
   api/[[...path]].js. Vercel then deploys a single ESM file: no TypeScript resolution at runtime, no .ts imports.
   pg stays external (a real dependency Vercel traces); the embedded PGlite engine is never referenced statically. */
import { build } from 'esbuild';
import { mkdirSync } from 'node:fs';

mkdirSync('api', { recursive: true });
await build({
  entryPoints: ['server/vercel.ts'],
  outfile: 'api/[[...path]].js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  external: ['pg', 'pg-native', '@electric-sql/pglite'],
  banner: { js: '/* generated by scripts/build-api.mjs; edit server/vercel.ts instead */\nimport { createRequire } from "node:module"; const require = createRequire(import.meta.url);' },
  logLevel: 'info'
});
