/* Generates src/data/land.js: which points of an even grid on the globe are land, for the dotted members globe.
   Source: Natural Earth 1:50m land (public domain) via the world-atlas package. The grid has a row every STEP degrees
   of latitude and, along each row, a dot every STEP degrees of arc, so dots sit evenly on the sphere like halftone.
   The cells that hold a member's city are always land, since every member works on land.

   It needs two packages that the site itself doesn't:
     npm i --no-save world-atlas@2 topojson-client@3 && node scripts/gen-land.mjs */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { feature } from 'topojson-client';
import { MEMBERS } from '../src/data/members.js';

const require = createRequire(import.meta.url);
const STEP = 1.25;
const topo = JSON.parse(readFileSync(require.resolve('world-atlas/land-50m.json'), 'utf8'));
const land = feature(topo, topo.objects.land);
const polys = land.features.flatMap((f) => (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates));
const boxes = polys.map((rings) => {
  let x0 = 180, x1 = -180, y0 = 90, y1 = -90;
  for (const [x, y] of rings[0]) { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }
  return [x0, y0, x1, y1];
});
const inRing = (x, y, ring) => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i], [xj, yj] = ring[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};
const isLand = (x, y) => polys.some((rings, k) => {
  const b = boxes[k];
  if (x < b[0] || x > b[2] || y < b[1] || y > b[3]) return false;
  return inRing(x, y, rings[0]) && !rings.slice(1).some((h) => inRing(x, y, h));
});

/* the same row layout the page decodes */
export const rowsOf = (step) => {
  const rows = [];
  for (let lat = 90 - step / 2; lat > -90; lat -= step) rows.push({ lat, n: Math.max(1, Math.round((360 * Math.cos((lat * Math.PI) / 180)) / step)) });
  return rows;
};
const rows = rowsOf(STEP);
const bits = [];
rows.forEach(({ lat, n }) => { for (let j = 0; j < n; j++) bits.push(isLand(-180 + ((j + .5) * 360) / n, lat) ? 1 : 0); });

/* every member's cell is land */
let forced = 0;
for (const m of MEMBERS) {
  if (m.lat == null || m.lng == null) continue;
  let offset = 0, best = null;
  rows.forEach(({ lat, n }, i) => {
    const j = Math.min(n - 1, Math.max(0, Math.floor(((m.lng + 180) / 360) * n)));
    const d = Math.abs(lat - m.lat);
    if (!best || d < best.d) best = { d, index: offset + j, i };
    offset += n;
  });
  if (!bits[best.index]) { bits[best.index] = 1; forced++; }
}

const bytes = new Uint8Array(Math.ceil(bits.length / 8));
bits.forEach((b, i) => { if (b) bytes[i >> 3] |= 1 << (i & 7); });
const b64 = Buffer.from(bytes).toString('base64');
const out = `/* Generated by scripts/gen-land.mjs from Natural Earth 1:50m land (public domain). Do not edit by hand.
   A grid with a row every ${STEP} degrees of latitude and, along each row, round(360 · cos(lat) / ${STEP}) evenly spaced
   points; bit i (least significant bit first) is 1 where point i is land. */
export const LAND = { step: ${STEP}, bits: '${b64}' };
`;
writeFileSync(new URL('../src/data/land.js', import.meta.url), out);
console.log(`land.js: ${bits.filter(Boolean).length} land points of ${bits.length}, ${forced} forced for members, ${b64.length} bytes`);
